# Generated by Django 3.2.6 on 2021-08-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boast_or_roast', models.BooleanField()),
                ('text', models.CharField(max_length=280)),
                ('vote_score', models.IntegerField()),
                ('upvotes', models.IntegerField()),
                ('downvotes', models.IntegerField()),
                ('submission_time', models.DateTimeField()),
            ],
        ),
    ]
